### ISSUE TITLE
Create Gandalf builder to configure library in the application class

### ISSUE THREAD

**Issue by btkelly** [btkelly/gandalf#10]
Create a builder pattern that allows the consumer to configure Gandalf for their specific use case. This will for sure include setting the url to fetch the update file. Not sure what else is required for the first release, custom JSON deserializer for sure at a later time.

Thoughts on other configurable features for the first release?

**Comment by jsibbold** [comment]
Web Caller
1. URL
2. Deserializer (later? I think we could get this in without a hitch)
Version Checker
1. Comparator of some sort that conveys a result to the Gandalf implementation.
Result Handler
1. Gandalf Interface (callbacks like onUpdateRequired, onUpdateOptional, onAlert, etc)

I feel like URL, Deserializer (I think that wouldn't be too bad), and Gandalf Interface are a good start. Also I split this up into basically the three steps, some of which will also require the shared preferences utility. Am I missing anything here?

**Comment by jsibbold** [comment]
We don't want them able to hook into the api callbacks do we?

**Comment by btkelly** [comment]
I wouldn't think so
