### ISSUE TITLE
Technology stack we talked about

### ISSUE THREAD

**Issue by btkelly** [btkelly/gandalf#14]
We decided on the following tech stack to get us to version 1.0, any objections or things to add to this list?

- OkHttp for networking
- GSON for JSON parsing
- SharedPrefs for storage
- AppCompat for dialog display
- Crashlytics if possible on a library project.

**Comment by macklinu** [comment]
:rocket:

**Comment by jsibbold** [comment]
All these changes sound great to me! But I could understand how some people might think the changes are bad. I don't know what to think.

**Comment by btkelly** [comment]
Ok cool, locked in for 1.0
