### ISSUE TITLE
Check to see if Crashlytics works with library projects

### ISSUE THREAD

**Issue by btkelly** [btkelly/gandalf#15]
We would like to know if we have crashes in Gandalf but I'm not sure how Crashlytics works with a library included in another app. Can we setup Crashlytics to send us reports when a consumer gets a crash?

**Comment by macklinu** [comment]
I'm not seeing any information on this in the Crashlytics support docs.

**Comment by btkelly** [comment]
I've emailed a guy on the Crashlytics team, we'll see if it's something they support at all.

**Comment by stkent** [comment]
@btkelly did they confirm no support?

**Comment by btkelly** [comment]
No response

**Comment by stkent** [comment]
No cookies?
