### ISSUE TITLE
Network call to pull down JSON for version information

### ISSUE THREAD

**Issue by btkelly** [btkelly/gandalf#3]
Just the network code that will pull down the JSON from the endpoint specified. This should include the ability for the consumer to configure the endpoint from which the JSON is pulled from.

**Comment by stkent** [comment]
You want to use Retrofit for this, correct?

**Comment by btkelly** [comment]
That is my thought, or at the very least OkHttp.

**Comment by stkent** [comment]
:+1:

**Comment by btkelly** [comment]
We decided to also use GSON for JSON parsing

**Comment by jsibbold** [comment]
and I believe just sticking to OkHttp correct? We'll just get the URL provided in the builder

**Comment by btkelly** [comment]
I don't think so

**Comment by btkelly** [comment]
Starting on this now
