### ISSUE TITLE
Major versions and minor versions not supported

### ISSUE THREAD

**Issue by bzabor** [btkelly/gandalf#56]
Looking at the source, gandalf does an Integer compare of the version numbers. It would be nice if it could do major and minor version number comparisons as well, such that:

v3.2 > v3.1
v3.12 > v3.8
v3.12.3 > v3.12.06

**Comment by btkelly** [comment]
True, we talked about it and decided the versionCode compare would be fine as it must be incremented with every release of the build. This would cover and major or minor releases.

**Comment by stkent** [comment]
Everything should be versionCode internally, right?

**Comment by bzabor** [comment]
Ah, I was thinking versionNumber, not versionCode. versionCodes are always integers. Using versionCodes makes total sense. Closing this issue.
