### ISSUE TITLE
The library is outdated in jcenter repository

### ISSUE THREAD

**Issue by vase4kin** [btkelly/gandalf#59]
Hey, I wasn't able to download the latest version of the library, the sources seem to be outdated. 
Here's my setup:
`compile 'com.btkelly:gandalf:1.2.1'`

**Comment by stkent** [comment]
Hi! I'm not sure what you mean when you say

> the sources seem to be outdated

As far as I can see, version 1.2.1 is still [available via JCenter](https://bintray.com/btkelly/maven/gandalf).

The first thing I'd double-check is that your build.gradle file is correctly looking for dependencies in JCenter (Gandalf is _not_ hosted on Maven Central). If that isn't the problem, please reply to this issue with the following information:

- A detailed description of what happens (console output, etc.) when you try to compile your application with the Gandalf dependency included;
- Your full build.gradle file.

Thanks!

**Comment by vase4kin** [comment]
Could you please have a look on [1.2.1 version sources](https://bintray.com/btkelly/maven/gandalf/1.2.1#files/com/btkelly/gandalf/1.2.1)? These sources don't contain last master code.

**Comment by stkent** [comment]
Ah, I see what you're saying now! Yes, v1.2.1 is behind the master branch ([by 12 commits, as of right now](https://github.com/btkelly/gandalf/compare/v1.2.1...master)). I'll ping @btkelly today and see if he's ready to ship a v1.3.0.

**Comment by vase4kin** [comment]
Sounds awesome, thanks!

**Comment by btkelly** [comment]
Ah, yup didn't' catch that. I'll post that up to jCenter today.

**Comment by btkelly** [comment]
A new version has been pushed to jCenter with the latest changes, version 1.3.0.
