### ISSUE TITLE
Auto install apk when using FileDownloadUpdateListener

### ISSUE THREAD

**Issue by kyhule** [btkelly/gandalf#69]
Have you consider initiating the apk install after downloading an apk using the FileDownloadUpdateListener? I have seen a few apps do this in the past so I know it can be done. If you wouldn't want to do this in the library, I can understand that, but maybe we could look into giving a callback instead of finishing the activity in onUpdateSelected. Let me know your thoughts.

**Comment by btkelly** [comment]
Well I left everything protected with the idea that if someone would like to change the default behaviour of the `FileDownloadUpdateListener` they can extend it and override just the methods they want. So in that case they would override the `onUpdateSelected` function and only call `downloadFile();` without the finish if they would like.

**Comment by kyhule** [comment]
I don't know how I overlooked that. That is completely acceptable. I am going to try and get that working. If I have something that works well, would you want me to document it so it can be part of the repo's wiki as an example implementation?

**Comment by kyhule** [comment]
Ahh, but the `downloadFile` method is private. That's why I was thinking you couldn't override `onUpdateSelected` without writing your own download method.

**Comment by kyhule** [comment]
Ahh, but `downloadFile` is private. That's why I thought you couldn't override `onUpdateSelected` without writing your own download logic.

**Comment by btkelly** [comment]
Ah, that was unintentional. I can update all methods to be protected to allow extension.

**Comment by vase4kin** [comment]
Hello,
> Ah, that was unintentional. I can update all methods to be protected to allow extension.

Is there any chance to get an update with these changes implemented? As i see it was merged, but no update was published.

**Comment by stkent** [comment]
I'll poke @btkelly today about getting an update shipped.

**Comment by btkelly** [comment]
Sorry about that, this one slipped through. I'll publish an update today.

**Comment by vase4kin** [comment]
Thanks much, guys.

**Comment by btkelly** [comment]
:+1: version 1.3.4 is now available.
