### ISSUE TITLE
Proposed update/message JSON structure

### ISSUE THREAD

**Issue by dtrenz** [btkelly/gandalf#7]
```json
{
	"android": {
		"alert": {
			"message": "We are currently performing server maintenance. Please try again later.",
			"blocking": true
		},
		"optionalUpdate": {
			"version": "3.9.0",
			"message": "A new version of the application is available, please click below to update to the latest version."
		},
		"requiredUpdate": {
			"version": "3.8.0",
			"message": "A new version of the application is available and is required to continue, please click below to update to the latest version."
		}
	}
}
```

**Comment by btkelly** [comment]
I like this, if there are no objections I say we go with this

**Comment by stkent** [comment]
The `version` keys could be a little more descriptively named. What does each represent?

**Comment by stkent** [comment]
Same for `blocking`, something like `blockUser` or `blockLaunch` seems a little clearer.

**Comment by btkelly** [comment]
Naming :facepunch:

**Comment by stkent** [comment]
![enhanced-buzz-6645-1374748131-4](https://cloud.githubusercontent.com/assets/6463980/12401858/45dc050a-bdf7-11e5-88bd-6f28f8efd773.jpg)

**Comment by btkelly** [comment]
Haha nice.

I'm down with being a little more verbose but I think it should remain the same in both message blocks so we can use the same models. Maybe like minimumVersion? And blockUser sounds fine.

**Comment by dtrenz** [comment]
gandalf json RFC-rev2:

```json
{
    "android": {
        "alert": {
            "message": "We are currently performing server maintenance. Please try again later.",
            "appLockout": true
        },
        "optionalUpdate": {
            "optionalVersion": "3.9.0",
            "message": "A new version of the application is available, please click below to update to the latest version."
        },
        "requiredUpdate": {
            "minVersion": "3.8.0",
            "message": "A new version of the application is available and is required to continue, please click below to update to the latest version."
        }
    }
}
```

**Comment by dtrenz** [comment]
I'm not sure that `minimumVersion` makes sense for an `optionalUpdate` since the optional update refers to a specific version, whereas the `requiredUpdate` refers to a range.

Maybe we should use a specific version string for `optionalUpdate` and use a Gemfile-style version for `requiredUpdate`: `"version": "< 3.9.0"`

**Comment by stkent** [comment]
@btkelly but those versions don't represent the same thing, so using the same model could get confusing in code. How about something like:

```json
{
    "android": {
        "transitoryAlert": {
            "message": "We are currently performing server maintenance. Please try again later.",
            "appLockout": true
        },
        "versionAlerts": {
            "latestVersionCode": 23,
            "oldestAllowedVersionCode": 12,
            "optionalUpdateMessage": "A new version of the application is available, please click below to update to the latest version.",
            "forcedUpdateMessage": "A new version of the application is available and is required to continue, please click below to update to the latest version."
        }
    }
}
```

**Comment by dtrenz** [comment]
I like the idea of referring to everything as alerts, but I have a few preferences:
 - The name `transitoryAlert` isn't very intuitive, for me.
 - Isn't `oldestAllowedVersionCode` the same as `minimumRequiredVersion`? I feel like "minimum required" is more commonly used phrasing than "oldest allowed."
 - On the hangout, we discussed that an optional update alert might not be for the current or latest version, so `latestVersionCode` wouldn't really work in that scenario.

I'm starting to think that we should table the design/structure of the general/transitory alert until we get to the next milestone.

**Comment by stkent** [comment]
1. Agreed, I ninja-edited to `highPriorityAlert` immediately after replying.
2. Yes, `minimumRequiredVersion` is a good substitute there!
3. When might we not want to alert the user of the latest available version?

**Comment by btkelly** [comment]
I'm up for adjustments and I'll do what everyone thinks but I think I'm in favor of the first posting of the structure still, with only some variable name changes.

**Comment by jsibbold** [comment]
I actually prefer the original JSON setup. I see the two blocks as just defining slightly different boundaries, for lack of a better term. `minimumVersion` (required is implied here yes?) is the hard boundary, `optionalVersion` is the soft boundary. They both have a message, the logic behind interpreting them is just slightly different.

**Comment by jsibbold** [comment]
`{
    "android": {
        "alert": {
            "message": "We are currently performing server maintenance. Please try again later.",
            "blocking": true
        },
        "optionalVersion": {
            "versionCode": 4,
            "message": "A new version of the application is available, please click below to update to the latest version."
        },
        "minimumVersion": {
            "versionCode": 2,
            "message": "A new version of the application is available and is required to continue, please click below to update to the latest version."
        }
    }
}`

Imagine in the above that the current store version is 5, in the case of someone having 4, they wouldn't actually get bothered to update to 5.

**Comment by stkent** [comment]
You guys do what you gotta do!

![thatll-work](https://cloud.githubusercontent.com/assets/6463980/12403296/23df5b82-be01-11e5-8aa6-0751903845f2.gif)

**Comment by dtrenz** [comment]
So, are we going to use version code for Android and version string for iOS?

**Comment by jsibbold** [comment]
I thought build number for iOS

**Comment by jsibbold** [comment]
well... I dunno I guess we could use strings for the version in iOS and ints for the version in Android, but that could get confusing? Strings for both?

**Comment by btkelly** [comment]
I like keeping them the same, my vote is strings for both

**Comment by jsibbold** [comment]
yep I'm cool with that

**Comment by btkelly** [comment]
OK so, are we cool with this, at least for milestone 1 (next milestone has custom json parsing)?

```json
{
	"android": {
		"alert": {
			"message": "We are currently performing server maintenance. Please try again later.",
			"blocking": true
		},
		"optionalUpdate": {
			"optionalVersion": "3.9.0",
			"message": "A new version of the application is available, please click below to update to the latest version."
		},
		"requiredUpdate": {
			"minimumVersion": "3.8.0",
			"message": "A new version of the application is available and is required to continue, please click below to update to the latest version."
		}
	}
}
```

**Comment by jsibbold** [comment]
:+1:

**Comment by dtrenz** [comment]
:shipit:
