### ISSUE TITLE
Gandalf not working in Samsung 10

### ISSUE THREAD

**Issue by atrang89** [btkelly/gandalf#86]
Anyone else having issues with a gandalf verifying if the app is coming from the play store?  I have a message coming up the app isn't the real app and blocks the users from the next process.  This is only occurring in Samsung 10 devices

**Comment by btkelly** [comment]
This doesn't sound like a Gandalf issue as at this point you are outside of Gandalf and interacting with the Play Store directly. This sounds like the download you are pointing the users to may be different from the application you are using Gandalf on or is at the very least signed with a different signing cert. Closing this issue as it's not resolvable through Gandalf changes.
